### ISSUE TITLE
Connection timed out : '/dev/hidraw0'

### ISSUE THREAD

**Issue by locar82** [dj-nitehawk/Hybrid-Inverter-Monitor#13]
I can see data from the inverter for about 2sec and then this error shows

 InverterMon.Server.InverterService.CommandExecutor[0]
      execution error: Connection timed out : '/dev/hidraw0'

**Comment by dj-nitehawk** [comment]
it's most likely caused by wifi dropouts or usb wire connectivity issues.
i've had similar issues with raspberry pi devices. was able to solve it by using a better power supply and an external usb dongle instead of the built-in wifi.

can't be certain though what the exact issue is in your setup.

and, there's not much i can do about it. you'd have to figure out and fix it on your end with your setup.
